openapi: "3.0.0"
info:
  title: Tshirt store Api
  description: learning creating e-commerse store
  version: 1.1.0
  contact:
    email: amit09yadav12@gmail.com
    url: "https://amityadav.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local hosts - for secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local hosts - for regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local hosts
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - dummy
      summary: return a greet message and current update
      responses:
        200:
          description: All good and success sign
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
